name: Fuzzer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Run at 3:10 and 14:10 UTC every day.
    - cron: '10 3,14 * * *' 
    
env:
  FINDINGS_DIR: pa193-bech32m-fuzzer/findings
  AFL_TIMEOUT: 60

jobs:
  fuzzer:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        fuzz-test: [ 'FuzzHrp', 'FuzzData', 'FuzzHrpAndData', 'FuzzCliHrpAndData',
            'FuzzCliWithHexInputFile', 'FuzzCliWithBase64InputFile', 'FuzzCliWithBinaryInputFile' ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Download and install AFL
      run: |
        wget http://lcamtuf.coredump.cx/afl/releases/afl-latest.tgz
        tar -xvf afl-latest.tgz
        cd afl-2.52b/
        wget https://github.com/Metalnem/sharpfuzz/raw/master/patches/RemoveInstrumentationCheck.diff
        patch < RemoveInstrumentationCheck.diff
        make
    - name: Restore dependencies
      run: dotnet restore
    - name: Build fuzzer project
      run: dotnet build --no-restore pa193-bech32m-fuzzer
    - name: Instrument the assembly
      run: |
        dotnet tool restore
        dotnet sharpfuzz pa193-bech32m-fuzzer/bin/Debug/net5.0/pa193-bech32m.dll
    - name: Set longer timeout when running on cron
      if: github.event.schedule == '10 3,14 * * *'
      # Run fuzzing for 10 hours
      run: echo "AFL_TIMEOUT=36000" >> $GITHUB_ENV
    - name: Run fuzzer
      env:
        AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES: 1
      run: (./afl-2.52b/afl-fuzz -m none -i pa193-bech32m-fuzzer/testcases -o $FINDINGS_DIR -t 5000 dotnet pa193-bech32m-fuzzer/bin/Debug/net5.0/pa193-bech32m-fuzzer.dll ${{ matrix.fuzz-test }}) & sleep $AFL_TIMEOUT; kill $!
    - name: Replace colons in findings
      if: always()
      run: |
        sudo apt-get install -y rename
        find $FINDINGS_DIR -name "*:*" -exec rename 's|:|-|g' {} \;
    - name: Save findings from fuzzing
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: fuzzer_findings
        path: ${{ env.FINDINGS_DIR }}
    - name: Fail if crashing inputs have been found
      if: always()
      run: \[ "$(ls -A $FINDINGS_DIR/crashes)" \] && { echo "Crashes found"; exit 1; } || echo "No crashes found."
