name: Fuzzer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  fuzzer:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Download and install AFL
      run: |
        wget http://lcamtuf.coredump.cx/afl/releases/afl-latest.tgz
        tar -xvf afl-latest.tgz
        cd afl-2.52b/
        wget https://github.com/Metalnem/sharpfuzz/raw/master/patches/RemoveInstrumentationCheck.diff
        patch < RemoveInstrumentationCheck.diff
        make
    - name: Restore dependencies
      run: dotnet restore
    - name: Build fuzzer project
      run: dotnet build --no-restore pa193-bech32m-fuzzer
    - name: Instrument the assembly
      run: |
        dotnet tool restore
        dotnet sharpfuzz pa193-bech32m-fuzzer/bin/Debug/net5.0/pa193-bech32m.dll
    - name: Run fuzzer
      env:
        AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES: 1
        TIMEOUT: 60
      run: (./afl-2.52b/afl-fuzz -m none -i pa193-bech32m-fuzzer/testcases -o pa193-bech32m-fuzzer/findings -t 5000 dotnet pa193-bech32m-fuzzer/bin/Debug/net5.0/pa193-bech32m-fuzzer.dll) & sleep $TIMEOUT; kill $!
    - name: Replace colons in findings
      if: always()
      run: |
        sudo apt-get install -y rename
        find pa193-bech32m-fuzzer/findings/ -name "*:*" -exec rename 's|:|-|g' {} \;
    - name: Save findings from fuzzing
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: fuzzer_findings
        path: pa193-bech32m-fuzzer/findings/
    - name: Fail if crashing inputs have been found
      if: always()
      run: 
