name: Fuzzer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  fuzzer:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Download and install AFL
      run: |
        wget http://lcamtuf.coredump.cx/afl/releases/afl-latest.tgz
        tar -xvf afl-latest.tgz
        cd afl-2.52b/
        make
    - name: Restore dependencies
      run: dotnet restore
    - name: Build fuzzer project
      run: dotnet build --no-restore pa193-bech32m-fuzzer
    - name: Instrument the assembly
      run: dotnet sharpfuzz pa193-bech32m-fuzzer/bin/Debug/net5.0/pa193-bech32m.dll
    - name: Run fuzzer
      env:
        AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES: 1
      run: ./afl-2.52b/afl-fuzz -i pa193-bech32m-fuzzer/testcases -o pa193-bech32m-fuzzer/findings -t 5000 dotnet pa193-bech32m-fuzzer/bin/Debug/net5.0/pa193-bech32m-fuzzer.dll
